export const dicView = {
    'en': {
      'UserID' : 'UserID',
      'bp_cd': 'BP_CD',
      "bp_type": "BP_TYPE",
      "bp_group": "BP_GROUP",
      "bp_rgst_no": "BP_RGST_NO",
      "bp_full_nm": "BP_FULL_NM",
      "bp_nm": "BP_NM",
      "bp_eng_nm": "BP_ENG_NM",
      "repre_nm": "REPRE_NM",
      "repre_rgst_no": "REPRE_RGST_NO",
      "fnd_dt": "FND_DT",
      "zip_cd": "ZIP_CD",
      "addr1": "ADDR1",
      "addr2": "ADDR2",
      "addr1_eng": "ADDR1_ENG",
      "addr2_eng": "ADDR2_ENG",
      "addr3_eng": "ADDR3_ENG",
      "contry_cd": "CONTRY_CD",
      "province_cd": "PROVINCE_CD",
      "currency": "CURRENCY",
      "tel_no1": "TEL_NO1",
      "tel_no2": "TEL_NO2",
      "fax_no": "FAX_NO",
      "home_url": "HOME_URL",
      "use_flag": "USE_FLAG",
      "bp_prsn_nm": "BP_PRSN_NM",
      "bp_contact_pt": "BP_CONTACT_PT",
      "bp_prsn_e_mail": "BP_PRSN_E_MAIL",
      "remark": "REMARK",
      "insert_id": "INSERT_ID",
      "insert_dt": "INSERT_DT",
      "updt_id": "UPDT_ID",
      "updt_dt": "UPDT_DT"
    },
    'ko': {
      'UserID' : '사용자ID',
      'bp_cd': '거래처코드',
      "bp_type": "거래처타입",
      "bp_group": "거래처그룹",
      "bp_rgst_no": "사업자번호",
      "bp_full_nm": "거래처전명",
      "bp_nm": "거래처명",
      "bp_eng_nm": "거래처영문명",
      "repre_nm": "대표자명",
      "repre_rgst_no": "대표자주민번호",
      "fnd_dt": "창립일",
      "zip_cd": "우편번호",
      "addr1": "주소1",
      "addr2": "주소2",
      "addr1_eng": "주소1_영문",
      "addr2_eng": "주소2_영문",
      "addr3_eng": "주소3_영문",
      "contry_cd": "국가코드",
      "province_cd": "지방코드",
      "currency": "통화코드",
      "tel_no1": "전화번호1",
      "tel_no2": "전화번호2",
      "fax_no": "팩스번호",
      "home_url": "홈페이지",
      "use_flag": "사용여부",
      "bp_prsn_nm": "거래처담당자",
      "bp_contact_pt": "거래처담당자연락처",
      "bp_prsn_e_mail": "거래처담당자 메일주소",
      "remark": "비고",
      "insert_id": "입력자",
      "insert_dt": "입력일자",
      "updt_id": "수정자",
      "updt_dt": "수정일자"
    }
}